version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    env_file:
      - ./.env
  
  frontend:
    # image: profcheg/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    # image: profcheg/foodgram_backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: sh -c "gunicorn backend.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - django_static_volume:/app/staticfiles/
      - media_volume:/app/media/
    depends_on:
      - db
      - frontend
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - django_static_volume:/usr/share/nginx/html/django_static/staticfiles/
      - media_volume:/usr/share/nginx/html/media/
    depends_on:
      - backend
    
volumes:
  django_static_volume:
  media_volume:
