# Generated by Django 3.2.12 on 2022-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220418_1350'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shopping_list_entry',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_entry'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shoppinglist_entry'),
        ),
    ]
